language: java
dist: trusty
before_install:
- cd ${TRAVIS_BUILD_DIR}/..
- git clone --depth=50 --branch=master https://github.com/vlingo/vlingo-common.git
- cd vlingo-common && mvn install -DskipTests=true
- cd ${TRAVIS_BUILD_DIR}/..
- git clone --depth=50 --branch=master https://github.com/vlingo/vlingo-actors.git
- cd vlingo-actors && mvn install -DskipTests=true
- cd ${TRAVIS_BUILD_DIR}
script:
- mvn install
deploy:
  provider: bintray
  file: bintray.json
  skip_cleanup: true
  user: d-led
  on:
    branch: master
  key:
    secure: bJRtWyB3YJtQ1BNLDlNSnnldiQjHHfqcvnCHBYCnlUMUa/KdjH0p9nUaLPTT3qKkduIX9bTkBlP191NTBXL+jJGf8A0ZpgbX3wJ9vJvfsm52uFlpm6i7Rv2k0dO9fVM9mVPpgmm5Wn65XaBKtpTmj6NUbmuBqJQI+uf8/VWmNlP0jUDGKVOzOxYhY1dhLDyYiCNkE3g3riDpWEFrtoAtExOmcr11g9Tv/pLW0W2KOfBnUQjj5Wrf0qpy9DsAAdSNndj48J+ZXpD36q6eSDKfhvMDnG3uAWCE+2+LsO+QX8IpWuSX9uG73N96WGc1lAKm51dXEqy4NOzC8kFsRjsfOZevip3ugX9rhbbxo+c/95W6JvLLWmr+096RpcOVU8sSmi/AEU4gS0T4s7fcFZj/uV8x/BqSc9w6yJIKP54Fw3FcYZSJ411iSNCqaglDwTN8hVtUEU3O/EOqWg2AenbtCBSRYKFg1tZVYZO1Jd5dfkpnZgrzCfpN3JtIHMSItEivWDzf7TKyf91KA8zA3zLWTJtsBQfEO1p9YPeF4C6h2G5j9aBVhKPuKwSPUL1zVUC0Yw0lYf3SBtqYquXsLqe/Cnq1z+ECMjF58q2L9yWcmeSV1kOdRxf6tat/F1U3j623S6HWgWe7D8eKkF502blyiO8+tNPPu5p1X92JA4nQHA4=
  passphrase:
    secure: jno/hK+LJjINavDAPfUnNcBtXYqih1HETU7TcaTJbo3zePzfXLJSx2YdVyXFRcf3yEnTIv2Ib7yyry3KSYBiMcZPFMOinP0jwERH+ylIfa0IsiEASwhytG1uTBiURhqQuLeST4FsL/sO/XEfGkfY585RzcnYEKyWpb59b69sqgs91T9uGZBDjnq+a1W+5qei02A63K+vK0vRzAFGhutLcSzIwgGnwjEDbXIXJnG9W9iuK9CGoGqIz50TCwWDek+gSNdTL5H/rjZqVPuIaetoqSd0kh3PFdkjSiHxQJ/mmNZWAM1o7H1TA+efywvCmKgan344d+LyKMkR3kVfb2yl7Rb0a2Bqd3g4+16omf0P53q1fZgPO+oRcXb6kC80jqKNGJX67sS8C1w1HpcVZp/tNuVmUzw/9/SmQ1G76IrWA3XTdmlgqvZUu+gH14dN24ofoBu6vWAmt2bKN3nBkp4Xck+eDnoe2zs6yaE0Q2WpM1ULLnpgzvxSlyGdJf2lf6w1DRoaoFF7B3cXqXMNF4X8N+rmJw8WcG4y7nndtuuIGxoCE+/aQWZCRB9Z7sByv2plaDuaXt/mgnA8lHCR/CZgAqgYRHHYEA9T8Jk+Fp20bC9kKd6j9Oa8kDaIpPQwy/I5jj536g/msctJykuFBh2nlJdCNFyVgX/xegDE2r0IC/g=
notifications:
  slack:
    secure: JMB8CNKmQqVpOJrzDUmj+k9EE2rEnGboc0EgQ7dVIXvsN6fJ5VMZcpPilYBn9az8afl8M1GL7UedCIXDwrIVVT8ah3AOwGjP3BxvMYVw+0gRuZTGPitBeMFLbgAZG+gYZUJeIu7QLqB4y6y7RQ/TJ6NlaqQQ5rxT2o2UW3ZzBBv9Z7zOs4mRL+DT92tq4ayHbEya7gURogpCykEtKCBVcnmA0587zhUdQkxLq8PSI5WmWx7RuqVpbfnk76Zp1O7mYnlKJHxurlbAiuL3fFAjjRsBwsdFjya/fTOTKMo8OHIaUacFJfmxEysit/+z55x/dE2yK3Qi+p7KsDULptv9n7peJz8CySrSjj5pZgVeGgagGI58eB5pkKMlhXgoAShyMCKji5CO1WGIKJ37VdCC9p1ECz2E1r8cGyzxvGvxcwQ5uPfjd3iiDgKK89v9w/hITetEcSPJgSix4LwJ/ddPnuVEiESBv8zFC3x0SLZYGMleDosml/Bw3abBpoym8bMk6KOxISw8eRrnYwgY3q9/P64FXRKZSxFLyJ5fuqfBeh4xQ/jk5m9Sh2ZY44D7eeNAG4Di0HpspYmzlcquA6be2nLWiNbqJuoyns3o+dcGBMWPpS953M8P+wRwh+3E/7NUkYX2cDqfHs3ZgPJM30V4YuyXlOjYqCQoX3Rf86qpd5I=
