language: java
dist: trusty
before_install:
- cd ${TRAVIS_BUILD_DIR}/..
- git clone --depth=50 --branch=master https://github.com/vlingo/vlingo-common.git
- cd vlingo-common && mvn install -DskipTests=true
- cd ${TRAVIS_BUILD_DIR}/..
- git clone --depth=50 --branch=master https://github.com/vlingo/vlingo-actors.git
- cd vlingo-actors && mvn install -DskipTests=true
- cd ${TRAVIS_BUILD_DIR}
script:
- mvn install
deploy:
  provider: bintray
  file: bintray.json
  skip_cleanup: true
  user: vaughnvernon
  on:
    branch: master
  key:
    secure: CtYTaIViiAXiMYAZEfWBbK2mWDG9heJsikxIZUuFKNRGPDu5SstdZmwh49fuj1gnek9nFypz3uXd5WKFeMX9V+Lp4BwkBDRu9OGjV5CFqjuyIOKuDIaq7dXpBOiIgYmrPTIFdVj7eEuWKI4uu//sjwtEC+TNLqwqil2y5MhZ+QUBYG8hRibIcMlQYJPJu6bftTyXbkmVVRpugfwH6SO3DIAqKZzOTzOReDIMW/BPIRM92NuW3W+1bSj8PSByk/Z8lSAWlinIw9sN+mxNDGAR7tEtGSWPD9F8UkGl4mpuZhydJqLl1m663ho0N0omukM20zfikmueQzgqt6cTgWraGeM7KAasNoIONwNiPetmSKoPpLjG6zQN6sXPWTwfAujUEcKTqRPRwFKUHHteTRNnBODUSQl/HGdbHpTrqxQFySznQ2qHukkVHn7JNonrD5D84j8hmN38k5P4Zvp7w0TiIaJ92GqUL5dzWx9H1sTh2oy5x1NIxNhoP495UGQ2G4GgrFeuMpJvprA8Ly8wKun4lB+IP6GxBnhp8+EYKNRItpx7HvQ+wiP7nxQBkpvZWbfqBopE6sahMO+BJER5c+Gq7/zZAnqn5oMnGCenOB3Nlgdmknl1lRHhX8AVM/n439SYfHAVNJ/8p5EtV8jW97iJGIZq7gNFgZ/fBl9KgaUf4XE=
  passphrase:
    secure: DWcRNjvNOjEB3iTIEmCIipVSPX12SXUiUgHzF4CtH7ZxyQzzsJzUsVweycrPcOe65SLZXZT4pkCMZiqd7joad3sG/J3s8SK8RAnuqqcPCn0or3yQrXqWJI6ux8QRV6vVb9DsRJNWQfu+PbsFCoQ1FqEaa60psjBwMeC2lbWU5ZwLxyuumuCDGlTrCJQHPZ6kVSevf/lCU2MO2KHSS76zTSKgPrE9p93Wfq4UswZWy+WRzBqYKosiu9pM0N1YExQxkLPZm128X8a+2C/nhCXSkEN9c2IOHim7w73eihAiQC63B4xKFpsyoZaPURdeEArDS0n5FvFOAlOF1wvIujqwBwsD+3AOMTNhM19iuSZ8S91LVewXEfbCj1VCXknnq3kYSm7w6IUdEfjDX4wYBwaIlyIv8tBHU9qD04u4aUFqA+BpykhfYXXtLW+scWedjbA4ALbK79sz1BIG/pBFP6Vch6dMAA2MF2z2Qtyq/hEZhItuDi+rl9iiwvUfbDRHnBvbPr7+qygNvaGIl/hflaQLejckdJ7nw8TJf5IXmJpZMsjtKYW29t66W2Bipbllc0HqzMwfG1+WAkIItNJKRSHkbbL7ggkgED9py8sLKs+ITFMUKBghfeOEv420v31r5x7MjN3hK+mokxz0IDmWseXKeZ+6EYEDefmia17hEkCJiiM=
notifications:
  slack:
    secure: AgEmeaQl5W+pb11ThGexSGdjQGHnkpOmRiQRBQbpcbG+B9JrItWirboKbLN4MlLMFz+sAX3IBI9LY09IcWT/ycmn4rXDIdfdfzH3edS5PXUkUZ3Ew8IaQ641OqZqhg/CbvacD/Pyv2gGCvF5UfRfKVrsNa7rQkGefP1mkQ4Z71bVxe+sokVDZYyInwVD5VuxIDCsmuM6AsbpQo8vGa6LvMlnqNhC5AYuOwWRntqrb6ncNYwuPUw5zT5cG43qr3iIlBP9uOr7+wgg1cAysMs3kd2uyq5g0hKvKY/HqW++BO7qWNLwnBdTcU0ibbr17znXfbgSfhG0shHWrzVE81hkAMpVD5uxWA1O6+VFnXvhicGQyZPR9zD4tyO1cge9KulU3xW2ZSO+vWJ0LahaszngFRaMETl7JtVddYJ8uT0Bsq8YyEaP9yOrXggt+MTp2XxtmTFCFdLs2T2BG7Ujz6+DsxbghYdTYN6lmhyZZSzPKqz/5/gpyo6HbP0byc4LQUM59RsG+sLckh9/FQHBAPwKgplcwiszMik/a2KnAlBrTasoXFWkfqeXrQJnZuDZp+JMs5Z9UMZeaGKrn+si8olBcMYEKOeoGsy2UrbSOMvwlew94C+6gSLfKOKhDswsCuMEj6B4ZAl4L1T3cvRRrVyViilTKbzhs9b2QBNXBBktJ2k=
