application:
  name: "account-service"
server:
  port: 8082
  maxBufferPoolSize: 100
  maxMessageSize: 131072
  dispatchers:
    factor: 1.5f
    count: 16
    throttlingCount: 4
    poolSize: 100
  processors:
    poolSize: 100
  actors:
    probeInterval: 2
    requestMissingTimeout: 2
datasources:
  default:
    url: ${JDBC_URL:`jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE`}
    username: ${JDBC_USER:sa}
    password: ${JDBC_PASSWORD:""}
    driverClassName: ${JDBC_DRIVER:org.h2.Driver}
jpa:
  default:
    packages-to-scan:
      - 'io.examples.account.domain'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: false