application:
  name: "Vlingo Application"
server:
  port: 8081
  maxBufferPoolSize: 100
  maxMessageSize: 65536
  dispatchers:
    factor: 1.5f
    count: 16
    throttlingCount: 4
    poolSize: 16
  processors:
    poolSize: 100
  actors:
    probeInterval: 200
    requestMissingTimeout: 200